version: "3.8"
services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
    command: ["redis-server", "--requirepass", "root"]
    networks:
      - mynetwork

  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - mynetwork

  worker:
    build:
      context: .
    container_name: rq_worker
    env_file:
      - .env
    command: rq worker --url redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
